#' IdentifyCutoff
#'
#' Identifies the optimal cutoff, i.e. lowest possible overtriage when
#' undertriage is at most 5%. If no cutoff has an undertriage of at most 5% then
#' it returns the cutoff associated with the lowest possible overtriage at the
#' lowest possible undertriage.
#' @param prediction A numeric vector. The predictions generated by the model to
#'     be tested. No default.
#' @param data A data.frame. The data in which to search for the optimal
#'     cutoff. No default.
#' @export
IdentifyCutoff <- function(prediction, data) {
    ## Get parameters
    major <- data$major
    unique.levels <- unique(prediction)
    ## Estimate under- and overtriage
    mistriage.list <- lapply(unique.levels, function(level) {
        undertriage <- CalculateUndertriage(level, prediction, major)
        overtriage <- CalculateOvertriage(level, prediction, major)
        return.object <- data.frame(level = level, undertriage = undertriage, overtriage = overtriage)
        return(return.object)
    })
    mistriage.data <- do.call(rbind, mistriage.list)
    ## Find optimal cutoff
    min.undertriage <- min(mistriage.data$undertriage)
    if (min.undertriage <= 0.05) {
        min.overtriage <- with(mistriage.data, min(overtriage[undertriage <= min.undertriage]))
        min.undertriage <- with(mistriage.data, undertriage[overtriage == min.overtriage])
    }
    if (min.undertriage > 0.05)
        min.overtriage <- with(mistriage.data, overtriage[undertriage == min.undertriage])
    cutoff <- with(mistriage.data, level[undertriage == min.undertriage & overtriage == min.overtriage])
    if (length(cutoff) > 1)
        cutoff <- sample(cutoff, 1)
    return(cutoff)
}
