#' IdentifyCutoff
#'
#' Identifies the optimal cutoff. First, it checks if there are cutoffs that
#' meet both criteria of an undertriage < 5% and an overtriage < 35%. Among
#' those cutoffs it selects the cutoff with the lowest overtriage. If there is
#' no such cutoff, it checks if there are cutoffs that results in a combined
#' mistriage (undertriage + overtriage) of < 40% and out of those selects the
#' cutoff with the lowest undertriage. If there are no such cutoff, it checks if
#' there are cutoffs with an undertriage of < 5% and among those it selects the
#' cutoff with the lowest overtriage. Finally, if neither of the previous checks
#' results in a cutoff, it selects the cutoff with the lowest undertriage.
#' @param prediction A numeric vector. The predictions generated by the model to
#'     be tested. No default.
#' @param data A data.frame. The data in which to search for the optimal
#'     cutoff. No default.
#' @export
IdentifyCutoff <- function(prediction, data) {
    ## Check that prediction most likely is a probability
    if (min(prediction) < 0 | max(prediction) > 1)
        stop ("prediction is not a probability")
    ## Get parameters
    major <- data$major
    potential.cutoffs <- seq(0, 1, 0.001)
    ## Estimate under- and overtriage
    mistriage.list <- lapply(potential.cutoffs, function(potential.cutoff) {
        undertriage <- CalculateUndertriage(potential.cutoff, prediction, major)
        overtriage <- CalculateOvertriage(potential.cutoff, prediction, major)
        return.object <- data.frame(potential.cutoff = potential.cutoff, undertriage = undertriage, overtriage = overtriage)
        return(return.object)
    })
    mistriage.data <- do.call(rbind, mistriage.list)
    ## Find optimal cutoff
    mistriage.data$mistriage <- with(mistriage.data, undertriage + overtriage)
    ## Check if there are cutoffs that meet both criteria of undertriage < 5%
    ## and overtriage of < 35% and among those select the cutoff with the lowest
    ## overtriage
    eligible.cutoffs <- with(mistriage.data, undertriage < 0.05 & overtriage < 0.35)
    cutoff.overtriage <- cutoff.undertriage <- NULL
    if (any(eligible.cutoffs)) {
        cutoff.overtriage <- min(mistriage.data$overtriage[eligible.cutoffs])
        cutoff.undertriage <- with(mistriage.data, undertriage[overtriage == cutoff.overtriage])[1]
    }
    ## Check if there are cutoffs that meet the criterion of a combined
    ## mistriage of < 40% and among those select the cutoff with the lowest
    ## overtriage
    eligible.cutoffs <- mistriage.data$mistriage < 0.4
    if (any(eligible.cutoffs) & is.null(cutoff.overtriage) & is.null(cutoff.undertriage)) {
        cutoff.undertriage <- min(mistriage.data$undertriage[eligible.cutoffs])
        cutoff.overtriage <- with(mistriage.data, overtriage[undertriage == cutoff.undertriage])[1]
    }
    ## Check if there cutoffs with an undertriage of < 5% and among those select
    ## the cutoff with the lowest overtriage
    eligible.cutoffs <- mistriage.data$undertriage < 0.05
    if (any(eligible.cutoffs) & is.null(cutoff.overtriage) & is.null(cutoff.undertriage)) {
        cutoff.overtriage <- min(mistriage.data$overtriage[eligible.cutoffs])
        cutoff.undertriage <- with(mistriage.data, undertriage[overtriage == cutoff.overtriage])[1]
    }
    ## Finally select the cutoff with the minumum undertriage regardless of
    ## associated overtriage
    if (is.null(cutoff.overtriage) & is.null(cutoff.undertriage)) {
        cutoff.undertriage <- min(mistriage.data$undertriage)
        cutoff.overtriage <- with(mistriage.data, overtriage[undertriage == cutoff.undertriage])[1]
    }
    ## Identify cutoff
    cutoff <- with(mistriage.data, potential.cutoff[undertriage == cutoff.undertriage & overtriage == cutoff.overtriage])
    if (length(cutoff) > 1)
        cutoff <- sample(cutoff, 1)
    return(cutoff)
}
